name: Build

on: [push]

jobs:
  build:
    runs-on: ${{matrix.preset.os}}
    strategy:
      fail-fast: false
      matrix:
        preset:
        - { os: windows-2019, configure: uqm-vs2019-x86,  build: uqm-vs2019-x86-debug }
        - { os: windows-2019, configure: uqm-vs2019-x86,  build: uqm-vs2019-x86-release }
        - { os: ubuntu-20.04, configure: uqm-make-gcc,    build: uqm-gcc-make-release }
        - { os: ubuntu-20.04, configure: uqm-make-clang,  build: uqm-clang-make-release }
        - { os: macos-10.15,  configure: uqm-make-clang,  build: uqm-clang-make-release }

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: cmake --preset ${{matrix.preset.configure}}

    - name: Build
      working-directory: ${{github.workspace}}
      run: cmake --build --preset ${{matrix.preset.build}}
